#user
User.create!(email: 'user@test.com', password: '123456', role: 0)
#editor
User.create!(email: 'editor@test.com', password: '123456', role: 1)
#admin
User.create!(email: 'admin@test.com', password: '123456', role: 2)

Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Art', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Art', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Art', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.second)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Art', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Travel', user: User.first)
Article.create!(title: Faker::Book.title, content: Faker::Quote.matz, category: 'Technology', user: User.first)
